In [2]:
#Q1. What is a database? Differentiate between SQL and NoSQL databases.
"""
A database is an organized collection of structured information, or data, typically stored electronically in a computer system.

                      SQL                                           |                   NoSQL
1.RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS)                     |  1.Non-relational or distributed database system.
2.These databases have fixed or static or predefined schema.        |  2.They have dynamic schema
3.These databases are not suited for hierarchical data storage.     |  3.These databases are best suited for hierarchical data storage.
4.These databases are best suited for complex queries               |  4.These databases are not so good for complex queries
5.Vertically Scalable                                               |  5.Horizontally Scalable         
6.Examples: MySQL, PostgreSQL, Oracle, MS-SQL Server, etc           |  6.Examples: MongoDB, GraphQL, HBase, Neo4j, Cassandra, etc

"""

In [ ]:
#Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.
"""
A data definition language (DDL) is a computer language used to create and modify the structure of database objects in a database.

CREATE: This command is used to create the database or its objects (like table, index, function, views, store procedure, and triggers).
DROP: This command is used to delete objects from the database.
ALTER: This is used to alter the structure of the database.
TRUNCATE: This is used to remove all records from a table, including all spaces allocated for the records are removed.
"""

In [ ]:
#Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.
"""
The data manipulation language statements are used to retrieve, add, delete, and modify the data that is stored in the objects of database.

1.INSERT:It is used to insert a new row in the database that is adding data to a table.
  Ex: INSERT into EMPLOYEE values (10, ‘Management’, ‘E01’, ‘John Abraham’);
  
2.UPDATE:It is used to update the data or row in the table.
  Ex: UPDATE employee set EMP_NO = E04 where DEPT_NO = 30;
  
3.DELETE:It is used to delete a row from the table in the database.
  Ex: DELETE from employee where DEPT_NO = 40;
"""

In [ ]:
#Q4. What is DQL? Explain SELECT with an example.
"""
DQL statements are used for performing queries on the data within schema objects. The purpose of the DQL Command is to get some schema 
relation based on the query passed to it.

SELECT: It is used to retrieve data from the database.
  Ex: SELECT * from Employee;
"""

In [ ]:
#Q5. Explain Primary Key and Foreign Key.
"""
Primary Key: A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. 
    It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 


Foreign Key: A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. 
    It is a column (or columns) that references a column (most often the primary key) of another table.
"""

In [4]:
#Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

import mysql.connector
 
mydb = mysql.connector.connect(
    host = "localhost",
    user = "yourusername",
    password = "your_password"
)

cursor = mydb.cursor()
cursor.execute("CREATE DATABASE Pwskills")

"""
A cursor in database is a construct which allows you to iterate/traversal the records of a table

The execute() method helps us to execute the query and return records according to the query.
"""

In [ ]:
#Q7. Give the order of execution of SQL clauses in an SQL query.
"""
SQL queries adhere to a specific order when evaluating clauses:
1. FROM/JOIN
2. WHERE
3. GROUP BY
4. HAVING
5. SELECT
6. ORDER BY
7. LIMIT/OFFSET
"""